### ISSUE TITLE
Have an option either per argument line or as a whole to not automatically add a whitespace between arguments.

### ISSUE THREAD

**Issue by F4w4r** [MBulli/SmartCommandlineArgs#107]
Working with Unreal 4 this tool is super useful, but unreal has a way of doing things... that sometimes makes it a bit painful.

See this
![image](https://user-images.githubusercontent.com/60370506/125784834-fd194894-1163-46c9-886f-681219b515d9.png)

Sometimes UE4's parser need the params to be in one big bundle and they use ? or , to separate items.

But if I leave ?Listen when it's not needed stuff won't even boot.
So I end up also having this one
![image](https://user-images.githubusercontent.com/60370506/125784999-fe5234f7-304e-4255-8e3f-bd73ba70054b.png)

If we could "aggregate" arguments without implicit whitespace between them, then I could have the following and simply activate my configuration instead of having every single configuration be fully defined in a single line

![image](https://user-images.githubusercontent.com/60370506/125785190-4f5633ad-8f7b-422c-be1f-bb2488c5fa85.png)

**Comment by gamagan** [comment]
I second this!
My usecase is similar. Sometimes, I want to have a switch that can take different options. It would be nice to have the switches in 1 entry, and the options separately. Currently, that's not possible because of the whitespace inserted.

![image](https://user-images.githubusercontent.com/9970152/132419869-aa6659c1-4f2c-4c96-817c-b2669fe6df45.png)

**Comment by Irame** [comment]
In the coming version there will be an option per group (and project) to disable the space delimiter.
This delimiter will be saved in the JSON-file, so you have the option to set any delimiter you wish there (eg. `"Delimiter": "?"`).
In the future we probably provide the option to set any delimiter via the extension window.

**Comment by F4w4r** [comment]
@Irame It seems this feature is gone in VS 2022 ?

There is no menu entry to edit the delimiter and if I am to put it inside the args.json manually it gets overriden.
