### ISSUE TITLE
Opening large solution for the first time

### ISSUE THREAD

**Issue by charleswfb** [MBulli/SmartCommandlineArgs#117]
After updating to the latest (2.3.1) version for VS2019, VS didn't respond for a few minutes.
Once in a while, a confirmation dialog would pop up, asking me if I would like to keep the default arguments from CMake.
This wouldn't be an issue if my solution didn't have 300+ projects and 10+ executables.

I understand a confirmation dialog is necessary for first-timers, but I would like to be able to turn off the confirmation altogether. 
Further, it would be nice if the UI wouldn't freeze while checking all my projects.

**Comment by MBulli** [comment]
Understandable. This was added due #105.
I think we need to add a "Don't ask again for this solution" checkbox @Irame .

**Comment by Irame** [comment]
I'm very sorry for the trouble.

Is it just the dialog that's annoying/problematic or is the long load time also a new problem?

**Comment by mg-jesp** [comment]
Ran into the same issue. Also if you regenerate the project files often, maybe you would still get the dialog every time the project is regenerated.
I added a new setting and turned off the dialog by default which solved it for me. #118

**Comment by Irame** [comment]
Thanks for the pull request.

However, I think this is not the right place for an option like this. Such an option only makes sense if its enabled by default to prevent data from being deleted.

My solution would be to make an Option in the Visual Studio settings under:
Tools → Options → Smart Commandline Arguments → General
There we could configure to ask or always accept/decline. (Always accepting would be the old behavior)
This option is saved in the Visual Studio settings and is therefore the same over all your projects (locally).

**Comment by mg-jesp** [comment]
Yes a global setting would be much better. 
The long loading time is a new problem and seam to be related to the dialogs. Another issue with the dialogs is that their height can exceed the screen which makes them unreadable and the button will be below the screen.

**Comment by charleswfb** [comment]
> I'm very sorry for the trouble.
> 
> Is it just the dialog that's annoying/problematic or is the long load time also a new problem?

No need to apologize. Thanks to you guys, command line args management is easier lol
I would say my biggest issue is I don't know when the dialog is coming up and I don't know when loading is finishing. I don't mind waiting if I need to wait.

I would personally add a simple "We're checking solution integrity" with a progress bar. The dialogs would be at the end? As necessary?
