### ISSUE TITLE
Out of memory exception after updating to 2.3.1

### ISSUE THREAD

**Issue by sleepyspider1** [MBulli/SmartCommandlineArgs#119]
VS2017 Pro
Project: Unreal 4
It started doing this immediately after updating to 2.3.1.
I have attached activitylog.xml and <project>.args.json in a zip file in the hopes you can reproduce it on your end.

The frame window contains the following message after a long visual studio hang:

```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\tseiler\AppData\Roaming\Microsoft\VisualStudio\15.0_bcd16563\ActivityLog.xml".

Exception details:
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
)
```

[BugData01.zip](https://github.com/MBulli/SmartCommandlineArgs/files/7866451/BugData01.zip)

**Comment by meo9979** [comment]
Hello. I had the same OOM while loading a solution that has over 330 projects. I looked at sleepyspider1's ActivityLog.xml and it's the same as what I had (sadly my log has been overwriten).

Just wanted to let you know that I did get & build the code from this pull request https://github.com/MBulli/SmartCommandlineArgs/pull/118 from mg-jesp fork and it fixes my issues, so this must be related to the dialog box (which I never saw pop-up).

**Comment by Irame** [comment]
I removed the dialog while we are working on a better solution to the problem. See [v2.3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.2) (also available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments)).
