### ISSUE TITLE
Solution with lots of projects freezing and crashing since last updates

### ISSUE THREAD

**Issue by ignomosabi** [MBulli/SmartCommandlineArgs#120]
Some OUT_OF_MEMORY condition

**Comment by ignomosabi** [comment]
Freezes while loading the VS2019 solution and ends up crashing. Had to revert to SmartCmdArgs-v2.2.0 to fix.

**Comment by ignomosabi** [comment]
Other solutions without that many projects work fine.

**Comment by Irame** [comment]
Thanks for the feedback.
Can you give more information on the type of solution you are working with, like the type of projects, the number of projects or the used Visual Studio version.
I would also be useful to know where and when the error occurs.
It would also be nice if you could attach the log file (see [Wiki/Debug Log](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log)).

**Comment by Irame** [comment]
I removed the dialog while we are working on a better solution to the problem. See [v2.3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.2) (also available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments)).
