### ISSUE TITLE
"no associated JSON file" and hang on load

### ISSUE THREAD

**Issue by DanQSplash** [MBulli/SmartCommandlineArgs#123]
Since updating to 2.3.1 we get a bunch of error messages like this when we load a solution:

![image](https://user-images.githubusercontent.com/91622691/149928202-b4a587a3-24b2-423f-a188-edbe5220a328.png)

It doesn't seem to matter if we press "Yes" or "No", VS hangs for a long time.

Downgrading to 2.2.0 (and disabling auto-update) seems to avoid the problem for now.

**Comment by Irame** [comment]
I removed the dialog while we are working on a better solution to the problem. See [v2.3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.2) (also available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments)).
