### ISSUE TITLE
Updated from 2.2 to 2.3.1 and a whole set of dialog errros show up about "VSC support is enabled"

### ISSUE THREAD

**Issue by santagada** [MBulli/SmartCommandlineArgs#124]
VisualStudio auto updated Smart Command Line args extension and after the update we get this error dialog for a lot of projects in our solution:

VSC support is enabled, and the project '{project.GetName()}' has no associated JSON file but the following arguments in the project configuration:\n\n{argsStr}\n\nShould they be cleared like the missing JSON file dictates?

1. Having a dialog per project is really bad as we have tons of projects so a lot of dialogs
2. What is VSC, and why can't it be disabled then? (I think the option should be spelled out in the error)
3. Saying no seems to break the extension as both the pane and the options have exceptions and don't work:

```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\leonardo.santagada\AppData\Roaming\Microsoft\VisualStudio\16.0_ac172aec\ActivityLog.xml".

Exception details:
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```

**Comment by MBulli** [comment]
The dialog was indeed an unfortunate decision. A user complained that our extension overrides the projects settings. 

We are currently working on a different approach to fix the complain. For now please use 2.2, we'll let you know when we fixed the 2.3 version.

**Comment by Irame** [comment]
I removed the dialog while we are working on a better solution to the problem. See [v2.3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.2) (also available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments)).

**Comment by santagada** [comment]
thanks for removing it in 2.3.2, visual studio with autoupdate will keep updating it, there's no way to pin an extension to a version in visual studio (or actually not even a nice way to downgrade an extension).
