### ISSUE TITLE
Fortran (*.vfproj) support

### ISSUE THREAD

**Issue by Irame** [MBulli/SmartCommandlineArgs#125]
We need the project type GUID for Fortran projects and the property name for the command line arguments within the project configuration.

**Comment by MBulli** [comment]
Or post the content of a Hello World project here.

**Comment by stevelongRBC** [comment]
Here is the contents of a sample *.sln file using Visual Studio 2017 and Intel Parallel Studio XE 2018:
`Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.28307.1738
MinimumVisualStudioVersion = 10.0.40219.1
Project("{6989167D-11E4-40FE-8C1A-2192A86A7E90}") = "QWin1", "QWin1.vfproj", "{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x86 = Debug|x86
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}.Debug|x86.ActiveCfg = Debug|Win32
		{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}.Debug|x86.Build.0 = Debug|Win32
		{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}.Release|x86.ActiveCfg = Release|Win32
		{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}.Release|x86.Build.0 = Release|Win32
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {3A34285E-2681-4CF5-902D-AE8F22B38E33}
	EndGlobalSection
EndGlobal`

**Comment by stevelongRBC** [comment]
Corresponding *.vfproj file:
```
<?xml version="1.0" encoding="UTF-8"?>
<VisualStudioProject ProjectCreator="Intel Fortran" Keyword="QuickWin" Version="11.0" ProjectIdGuid="{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}">
	<Platforms>
		<Platform Name="Win32"/></Platforms>
	<Configurations>
		<Configuration Name="Debug|Win32">
				<Tool Name="VFFortranCompilerTool" SuppressStartupBanner="true" DebugInformationFormat="debugEnabled" Optimization="optimizeDisabled" WarnInterfaces="true" Traceback="true" BoundsCheck="true" StackFrameCheck="true" RuntimeLibrary="rtQuickWinDebug"/>
				<Tool Name="VFLinkerTool" LinkIncremental="linkIncrementalNo" SuppressStartupBanner="true" GenerateDebugInformation="true" SubSystem="subSystemWindows"/>
				<Tool Name="VFResourceCompilerTool"/>
				<Tool Name="VFMidlTool" SuppressStartupBanner="true"/>
				<Tool Name="VFCustomBuildTool"/>
				<Tool Name="VFPreLinkEventTool"/>
				<Tool Name="VFPreBuildEventTool"/>
				<Tool Name="VFPostBuildEventTool"/>
				<Tool Name="VFManifestTool" SuppressStartupBanner="true"/></Configuration>
		<Configuration Name="Release|Win32">
				<Tool Name="VFFortranCompilerTool" SuppressStartupBanner="true" RuntimeLibrary="rtQuickWin"/>
				<Tool Name="VFLinkerTool" SuppressStartupBanner="true" SubSystem="subSystemWindows"/>
				<Tool Name="VFResourceCompilerTool"/>
				<Tool Name="VFMidlTool" SuppressStartupBanner="true"/>
				<Tool Name="VFCustomBuildTool"/>
				<Tool Name="VFPreLinkEventTool"/>
				<Tool Name="VFPreBuildEventTool"/>
				<Tool Name="VFPostBuildEventTool"/>
				<Tool Name="VFManifestTool" SuppressStartupBanner="true"/></Configuration></Configurations>
	<Files>
		<Filter Name="Header Files" Filter="fi;fd;h;inc"/>
		<Filter Name="Resource Files" Filter="rc;ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe">
		<File RelativePath=".\Resource1.rc"/></Filter>
		<Filter Name="Source Files" Filter="f90;for;f;fpp;ftn;def;odl;idl">
		<File RelativePath=".\Source1.f90"/></Filter></Files>
	<Globals/></VisualStudioProject>
```

**Comment by MBulli** [comment]
@stevelongRBC  Thanks, can you please set some command lines in the project properties and post the project file (*.vfproj)  again?

**Comment by stevelongRBC** [comment]
I added two dummy arguments, as shown below:
![image](https://user-images.githubusercontent.com/77281243/150562117-1174fd25-42da-4e03-a9c7-9fc5767fa42c.png)

This results in the creation of a user-specific "*.vfproj.[username].user" file (no changes to the main *.vfproj file).

```
<?xml version="1.0" encoding="UTF-8"?>
<VisualStudioUserFile ProjectCreator="Intel Fortran" Keyword="QuickWin" Version="11.0" ProjectIdGuid="{BA67A2F9-68AB-4E6E-8CF4-6B033A0D3370}">
	<Configurations>
		<Configuration Name="Debug|Win32" CommandArguments="arg1 arg2"/>
		<Configuration Name="Release|Win32"/></Configurations></VisualStudioUserFile>

```

**Comment by Irame** [comment]
Ok, I found the right thing to download, I think. I'm now using the *Intel® oneAPI HPC Toolkit* which includes a Fortran compiler to make this work. Projects created with this have the same GUID and the same `.user` file structure, so it should be the right tool.

**Comment by Irame** [comment]
I made a version including the Fortran support for you to test it. (You have to uninstall the extension first.)
[SmartCmdArgs-v2.3.2-FortranTest.vsix.zip](https://github.com/MBulli/SmartCommandlineArgs/files/7918258/SmartCmdArgs-v2.3.2-FortranTest.vsix.zip)
