### ISSUE TITLE
The global "Enable version control support" setting is not available in VS2019

### ISSUE THREAD

**Issue by vrubleg** [MBulli/SmartCommandlineArgs#132]
I wanted to turn off this setting:

> Tools → Options → Smart Commandline Arguments → General → Enable version control support

But seems like there is no such setting:
![image](https://user-images.githubusercontent.com/2157439/172685538-d900b8a7-db54-40fc-9f96-f34d6e6c8891.png)

I don't ever need to commit my temporary debug settings, so I would like to disable this new feature for all projects.

**Comment by Irame** [comment]
We moved this option to the "wrench" icon but it will be saved to a JSON file.
This doesn't solve your problem I think because you don't want additional files in the project.
We could bring back a global default or something which takes precedence if there is no JSON config file.

**Comment by vrubleg** [comment]
Yeah, it would be great if there is a global default that disables creation of this file.

**Comment by vrubleg** [comment]
Thank you so much!

**Comment by Irame** [comment]
FYI: There was a bug in the 2.4 version where the options where not saved. I've fixed it and released the fixed version 2.4.1.
