### ISSUE TITLE
Backslash issue with arguments on 17.2.3

### ISSUE THREAD

**Issue by nmoinvaz** [MBulli/SmartCommandlineArgs#133]
In recent version of Visual Studio 17.2.3 and SmartCommandLineArgs 2.3.0, arguments that contain backslash n are sent to the application as a new line character.
```bash
--my_arg=c:\users\nathan\source\myfile.txt
```

![image](https://user-images.githubusercontent.com/1364432/173703013-4d483593-3954-4078-bfd2-2b8535decc96.png)

- This appears to work fine on Visual Studio 17.1.5 and SmartCommandLineArgs 2.3.0.
- If I use forward slashes instead of backslash it parses the argument value properly. 
- If I run via the command line in a Developer Terminal then it works properly, so it seems to be something with SmartCommandlineArgs: ![image](https://user-images.githubusercontent.com/1364432/173703414-c3e0db3b-a2e2-4f7a-9d4b-6af1750e88c3.png)

**Comment by Irame** [comment]
I could not reproduce this. Is it still the case with 17.5 and 2.3.2?

**Comment by nmoinvaz** [comment]
It does not reproduce on 2.3.2: 

![image](https://user-images.githubusercontent.com/1364432/221724387-9180503f-cc76-4033-8605-909265d9840c.png)

Thanks.
