### ISSUE TITLE
Split command line arguments not showing in 2022

### ISSUE THREAD

**Issue by nmoinvaz** [MBulli/SmartCommandlineArgs#138]
Using version 2.3.0.
See #70

![image](https://user-images.githubusercontent.com/1364432/187795774-f3e5cf42-f90b-4c6b-a05a-9402330f8dca.png).

The menu item doesn't show up anymore.

**Comment by Irame** [comment]
Is this still the case with [v2.3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.3.2)?

**Comment by nmoinvaz** [comment]
It is fixed in 2.3.2. Thanks.
