### ISSUE TITLE
No Commandline Arguments window in VS22 Version 17.4.3

### ISSUE THREAD

**Issue by FedericoGnesotto** [MBulli/SmartCommandlineArgs#142]
Unfortunately after upgrading the window is gone

**Comment by nmoinvaz** [comment]
I am using VS 2022 17.4.4 and the window is visible. Perhaps you need to re-add it to your window layout from the `View > Other Windows > Command Line Arguments` menu. Or try to reinstall the plugin?

**Comment by Irame** [comment]
I could not reproduce this by upgrading to 17.5.0 and extension version 2.3.2.

**Comment by FedericoGnesotto** [comment]
Most probably an issue of my pc with windows 11 as formatting seems to have solved the issue
