### ISSUE TITLE
Not compatible with Oasis NX (Switch) which uses "Remote Command Arguments"

### ISSUE THREAD

**Issue by sorenr** [MBulli/SmartCommandlineArgs#143]
First, thanks for an excellent extension. I use Smart Command Line Arguments every day and find it invaluable.

Smart Command Line Arguments works great for developing on PC, Xbox, and Playstation but not in the "Oasis NX" (Switch) environment.

The issue might be that Smart Command Line Arguments sets "Command Arguments":
![image](https://user-images.githubusercontent.com/1168032/218464655-afb4d618-dbe4-4df7-ac1b-013ea929007c.png)

... whereas Oasis NX requires "Remote Command Arguments":
![image](https://user-images.githubusercontent.com/1168032/218464711-62ab40c9-be60-4c16-898c-836a22c4d940.png)

This might work with a configurable variable designating the name of the debugging field to set.

**Comment by Irame** [comment]
Hi, tanks for the kind words.
I didn't find any place to download "Oasis NX", so I couldn't look myself.

Could you please [enable logs](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log) and then try to set the command line arguments with the extension and attach the log file.

I would also need the *.user file it should look something like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <LocalDebuggerCommandArguments>Test</LocalDebuggerCommandArguments>
    <RemoteDebuggerCommandArguments>Test</RemoteDebuggerCommandArguments>
  </PropertyGroup>
</Project>
```
The relevant part is the tag that encloses the arguments.

**Comment by sorenr** [comment]
I've enabled logs and I have a logfile. Are there particular lines that I can send you? This is for a proprietary, high exposure project and I'd rather not upload a whole logfile with special flags and other general interest keywords to a searchable public website.

Here's a *.user file which is very similar to the one I'm using:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|NX64'">
    <LocalDebuggerCommandArguments>+server redacted -foo -bar</LocalDebuggerCommandArguments>
    <NXTargetSerialNumber>XAL0REDACTED00</NXTargetSerialNumber>
    <NXTargetName>Default</NXTargetName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|NX64'">
    <NXTargetName>Default</NXTargetName>
    <LocalDebuggerCommandArguments>-notimeout +comms_newchatserver 0</LocalDebuggerCommandArguments>
    <NXTargetSerialNumber>XAL0REDACTED00</NXTargetSerialNumber>
    <RemoteDebuggerCommandArguments>-software redacted +environment redacted -foo -bar</RemoteDebuggerCommandArguments>
    <DebuggerFlavor>OasisNXDebugger</DebuggerFlavor>
  </PropertyGroup>
</Project>
```

**Comment by Irame** [comment]
I am sorry, I was mistaken. We don't need the Log file. It seems the *.user file has everything we need.
I will create a test version for you some time this evening. Which Visual Studio version are you using?

**Comment by sorenr** [comment]
We're currently using Visual Studio 2019.

**Comment by Irame** [comment]
Here is the test version:
[SmartCmdArgs-2019-v2.3.2-test.vsix.zip](https://github.com/MBulli/SmartCommandlineArgs/files/10852529/SmartCmdArgs-2019-v2.3.2-test.vsix.zip)
(had to zip it because GitHub doesn't like *.vsix files)

**Comment by sorenr** [comment]
Confirmed! The above version lets me launch to a devkit with configurable arguments.

**Comment by Snowapril** [comment]
@Irame Hello, I'm also having trouble with using SmartCommandLineArgs for switch2 build. Could you also add support for below stuffs?
```c++
            ("NintendoGDBDebugger", "RemoteDebuggerCommandArguments"),
            ("NintendoLLDBDebugger", "RemoteDebuggerCommandArguments"),
```
Thanks!
