### ISSUE TITLE
Extension Published Twice in the Marketplace

### ISSUE THREAD

**Issue by jleaders** [MBulli/SmartCommandlineArgs#144]
A duplicate extension is published in the VS Marketplace with an identical name, and icon,

https://github.com/MBulli/SmartCommandlineArgs
vs
https://github.com/pedoc/SmartCommandlineArgs 

I notice the donation link differs but not sure what else

![image](https://user-images.githubusercontent.com/2430917/224440208-228d6f83-09f6-4459-ad9e-971b561456c5.png)

**Comment by Irame** [comment]
Yea I know, but it seams that they already removed it form the marketplace.
I wrote them in the Q&A section, that I am one of the authors and uploaded an updated version for 2022 to the marketplace.
