### ISSUE TITLE
Custom prefix/postfix/delimiter for groups

### ISSUE THREAD

**Issue by Gargaj** [MBulli/SmartCommandlineArgs#154]
Use case: In Unreal Engine, you can specify a command line flag called `ExecCmds` where you can feed automatic variables into the game - however, you can only specify one such flag, which is then follows with a string that can have several variables.

Example: `-ExecCmds="GameSpeed 1,Gravity 1.84,PlayerName 'John Doe',Invincibility 1"`

In this case, often I need to toggle the above variables independently depending on the situation, and my optimal UX in this case would be a command line group where I can specify `-ExecCmds="` as the prefix, `"` as the postfix, and `,` as the delimiter, and just toggle the options internally:

![image](https://user-images.githubusercontent.com/1702533/234261593-6c3fe368-7260-4f9c-8524-644cd3468776.png)

(Note that this would be only for that group, and then the rest of the command line arguments would just arrive with the standard space-delimiter as normal.)

**Comment by Irame** [comment]
Thanks for the request!

We already support "custom" delimiters but they can only be set to `" "` or `""`.
If you set it to `""` it will be saved to the JSON file and you can edit it there two what ever you like.

As for prefix and suffix, I would suggest you create a group with the delimiter set to `""` and in that group have the first argument be `-ExecCmds="` and the last be `"` and in between those arguments a group with your options `GameSpeed 1,Gravity 1.84,PlayerName 'John Doe',Invincibility 1` where the delimiter is set to `,` in the json.

I think that adding a prefix/postfix option would bloat the UI a bit and is not really necessary if you can accomplish it relative easy with existing tools . I agree that it is inkonvenient to customize the delimiter in the way I described it and I want to change that in the future.

**Comment by Gargaj** [comment]
> I agree that it is inkonvenient to customize the delimiter in the way I described it and I want to change that in the future.

To be fair, if you're adding a popup window (I assume) for changing the delimiter, I don't think prefixes/postfixes would be a step too far from there either.

**Comment by Irame** [comment]
implemented in 31e6f39e263fa1d7c33ac20966bfa9c7582c4bc5 and available in [v2.6.0](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.6.0)
