### ISSUE TITLE
SetSite failed for package [CmdArgsPackage]

### ISSUE THREAD

**Issue by mauriziodepascale** [MBulli/SmartCommandlineArgs#163]
Hi,
I've been using the extension successfully for many weeks. Then it started failing to load (same exact codebase).
After a bit the same issue showed up on a second machine (same codebase) and a third one (idem), so it doesn't seem to be machine-specific, and either codebase-triggered or a bug in the extension.
I tried clearing some of the .vs caches and similar folders, but the problem persists.

Here are the last two entries from the ActivyLog.xml:

`<entry>
    <record>361</record>
    <time>2023/11/28 08:14:42.113</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Gathering commands from configurations for project &apos;app.engine&apos;.</description>
  </entry>
  <entry>
    <record>362</record>
    <time>2023/11/28 08:14:42.183</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CmdArgsPackage]Source: &apos;Anonymously Hosted DynamicMethods Assembly&apos; Description: The best overloaded method match for &apos;System.Collections.Generic.List&lt;SmartCmdArgs.Logic.CmdArgumentJson&gt;.Add(SmartCmdArgs.Logic.CmdArgumentJson)&apos; has some invalid arguments&#x000D;&#x000A;</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>0x80131500</hr>
    <errorinfo></errorinfo>
  </entry>`

  

![image](https://github.com/MBulli/SmartCommandlineArgs/assets/11369769/bb857018-bdd8-411e-ac06-7d51ef361447)

it would be great if you could look into it - happy to help with reproing.

Thanks,
Maurizio

**Comment by Irame** [comment]
Hi, thanks for using the extension and writing this issue. I haven't had time to maintain this extension recently, sorry.
I did some rather big project restructuring and added a few features in the latest beta build.
Could please try preview version [2.6.0.3](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.6.0.3) and check if your issue still persists?

**Comment by Marc-IV** [comment]
I get the same error message using Microsoft Visual Studio Professional 2022, Version 17.8.7, and the the preview version 2.6.0.3 shows the same behavior.

Here are the recordings in the ActivityLog.xml

 <entry>
    <record>2046</record>
    <time>2024/04/02 12:19:43.351</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CmdArgsPackage]</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
  </entry>
  <entry>
    <record>2047</record>
    <time>2024/04/02 12:19:43.501</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function LoadDTETypeLib</description>
  </entry>
  <entry>
    <record>2048</record>
    <time>2024/04/02 12:19:43.501</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Leaving function LoadDTETypeLib</description>
  </entry>
  <entry>
    <record>2049</record>
    <time>2024/04/02 12:19:43.518</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2050</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2051</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2052</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2053</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2054</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2055</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2056</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2057</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2058</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2059</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2060</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2061</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2062</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2063</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2064</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2065</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2066</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2067</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2068</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2069</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2070</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2071</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2072</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2073</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2074</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2075</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2076</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2077</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2078</record>
    <time>2024/04/02 12:19:43.519</time>
    <type>Warning</type>
    <source>SmartCommandlineArgs</source>
    <description>[1] Could not retrieve property with id=-2120 from hierarchy</description>
  </entry>
  <entry>
    <record>2079</record>
    <time>2024/04/02 12:19:43.536</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CmdArgsPackage]Source: &apos;Microsoft.VisualStudio.Shell.Framework&apos; Description: GetDialogPage must be called on the UI thread.&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8001010E): GetDialogPage must be called on the UI thread.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.GetDialogPage[Page]()&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)&#x000D;&#x000A;   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at SmartCmdArgs.Services.OptionsSettingsService.InitializeAsync()&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.&lt;InitializeAsyncServices&gt;d__25.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.&lt;InitializeAsync&gt;d__23.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>0x8001010e</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by kim2048** [comment]
Hello, same here with VS Professional 2022 17.9.5 😢

**Comment by Irame** [comment]
Unfortunately I can't reproduce the issue, but I tried to fix it anyway.
Could you please try [v3.0.1](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v3.0.1) and give me feedback if the issue is solved or not, thanks!

**Comment by Marc-IV** [comment]
It still does not work with v3.0.1.

` <entry>
    <record>464</record>
    <time>2024/04/03 07:05:06.505</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CmdArgsPackage]</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
  </entry>
  <entry>
    <record>465</record>
    <time>2024/04/03 07:05:06.568</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [CmdArgsPackage]Source: &apos;mscorlib&apos; Description: Exception has been thrown by the target of an invocation.&#x000D;&#x000A;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.Runtime.InteropServices.COMException: GetDialogPage must be called on the UI thread.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.GetDialogPage[Page]()&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)&#x000D;&#x000A;   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage..ctor()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.Runtime.InteropServices.COMException (0x8001010E): GetDialogPage must be called on the UI thread.&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.GetDialogPage[Page]()&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)&#x000D;&#x000A;   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)&#x000D;&#x000A;   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage..ctor()</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>0x80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>`

**Comment by Irame** [comment]
Its a bummer that I can't reproduce the issue and have to do fixes that should fix the problem instead of fixes that actually fix the problem...
Here is another try: [v3.0.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v3.0.2)

**Comment by Irame** [comment]
Im tagging this as a duplicate, please continue the conversation in issue #177.
