### ISSUE TITLE
Dotnet core project support

### ISSUE THREAD

**Issue by trymnilsen** [MBulli/SmartCommandlineArgs#20]
Creating a dotnet core console application gives the "No supported startup project found". Simply creating a dotnet core console project should be enough to reproduce.

**Comment by MBulli** [comment]
It seems that Core projects don't expose the command line arguments as properties.
That means that our way to set the arguments won't work.

We need to figure out something else. Right now we're quite busy thus PRs are more than welcome :)

**Comment by MBulli** [comment]
Done! Implemented in e67d8532e9abb6b13eec08a9b211311bde0b144a.
