### ISSUE TITLE
Command line stay blank in VS2017 RC.3

### ISSUE THREAD

**Issue by galop1n** [MBulli/SmartCommandlineArgs#21]
The commandline argument window is here, i can manipulate it, but the arguments are never used

**Comment by MBulli** [comment]
What kind of project are you using?
Also you might want to enable logging and send us the log file.
[See this link](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v1.2.1) to see how to enable logging.

**Comment by galop1n** [comment]
Here the log,

I also notice that the plugin is now unable to even open the original json, and on a save all, it will blank out the file. This is with a C++ project managed with the Git Team Explorer.

[ActivityLog.txt](https://github.com/MBulli/SmartCommandlineArgs/files/742837/ActivityLog.txt)

**Comment by MBulli** [comment]
Thak you for the log file. We were able to reproduce the problem. 
It seems that its a bug in VS. For now we're going to wait for the next RC or the RTM. Sorry.

**Comment by psallandre** [comment]
I can confirm that there are some troubles with VS2017 RTM.
The args.json file is not read when the project is loaded, and whatever the arguments we fill in the commandline window, they are not used.
Here are 2 logs with the same project created by cmake respectively for VS2015 and VS2017
[ActivityLog_15.0_eadf1e8b.txt](https://github.com/MBulli/SmartCommandlineArgs/files/831048/ActivityLog_15.0_eadf1e8b.txt)
[ActivityLog_14.0.txt](https://github.com/MBulli/SmartCommandlineArgs/files/831051/ActivityLog_14.0.txt)

So, I can't use VS2017 for now! I'm a SmartCommandlineArgs addict ;) Thanks for this really useful extension.

**Comment by MBulli** [comment]
Thanks. Sadly microsft broke our way of setting the properties.
Right now we try to figure out a new way.

**Comment by MBulli** [comment]
@galop1n @psallandre  Should be fixed in the latest version
