### ISSUE TITLE
VSFunnel + SmartCommandLineArgs: Command Line Arguments Don't Stick Between SLN Reloads

### ISSUE THREAD

**Issue by eddieparker** [MBulli/SmartCommandlineArgs#23]
Love this plugin: but I also love VSFunnel: https://marketplace.visualstudio.com/items?itemName=DimitriDering.Funnel

If I have both of them installed, SmartCommandLineArgs forgets what args it had between loads.  Not sure if it's VSFunnel causing the issue, or the combination of it + SmartCommandLineArgs, but I'd love if these two worked well together.

**Comment by Irame** [comment]
The new version should fix this issue if u have VCS enabled.

**Comment by Irame** [comment]
The [latest version](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v1.4.0) should fix this issue completely.
