### ISSUE TITLE
Significant delay after every operation

### ISSUE THREAD

**Issue by Leon99** [MBulli/SmartCommandlineArgs#25]
VS2017. Doing any action in the Commandline Arguments involves a couple of seconds delay.

**Comment by Irame** [comment]
Hi, thanks for the report, this should be fixed in the [latest version](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v1.4.0) which should be available over the marketplace shortly.

**Comment by Leon99** [comment]
Thanks, looking forward to it - great extension otherwise!
