### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by Leon99** [MBulli/SmartCommandlineArgs#26]
On VS2017, pressing the copy to clipboard button shows 

> OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))

**Comment by Irame** [comment]
Hi, thanks for the report.
I could not reproduce the error myself so I would like to know if it occurs frequently, if there is a pattern to it or if there are steps I can take to reproduce it.
