### ISSUE TITLE
Suggestion of a Feature: Groups/Filter

### ISSUE THREAD

**Issue by vincentkarlsson94** [MBulli/SmartCommandlineArgs#28]
Suggestion: It would be great if you would add Groups or Filter of some sort.
For me that have many projects with a lot of command line arguments there would be great with the option to minimize them.

Maybe like the Insert of a item buttons, there could be two more for creating Groups or just select some items, right click -> create group.

**Comment by Irame** [comment]
Hi, thanks for the suggestion! 
We already thought about implementing such a feature but then VS 2017 came along and we had to make a lot of changes to keep out extension compatible.
Its nice to see the demand for such a feature though and now where everything seems to work fine we can have another look at it.

**Comment by dvbvolkm0** [comment]
Could you please pick up on this suggestion :)

We are using your tool with a lot of command line arguments. Grouping and a text search filter would really help us.

Your work is much appreciated !!!

**Comment by MBulli** [comment]
Thank you @SolarX6 :)
I'm afraid I have to hold this issue back until we have some spare time. Right now both of us are very busy.
But I'm optimistic that we can resume our work on this project in a month or so.

**Comment by MBulli** [comment]
@vincentkarlsson94 @SolarX6 We just released the new version! Feel free to check out the new grouping feature.

**Comment by SolarX6** [comment]
@MBulli  Thank you very much. We are using the new version for a while now. It is just a great improvement :)

One little thing: Horizontal scrolling of the view is a bit off. If you select a row the checkbox will always be aligned to the left border of the view. If the row is in a lower hierarchy level, it will scroll the little arrows of the nodes of of sight. This is when the rows exceed the width of the view (which is mostly the case).

Once again: Great work 👍

**Comment by MBulli** [comment]
@SolarX6 Thanks :) Yes the scrolling is annoying and needs to be fixed. See #40
