### ISSUE TITLE
Doesn't apply arguments to Remote Windows Debugger

### ISSUE THREAD

**Issue by jfmarquis** [MBulli/SmartCommandlineArgs#29]
It only applies the command line to Local Windows Debugger.

In Microsoft.VisualStudio.VCProjectEngine, there is Command, CommandArguments (the one updated) and RemoteCommand; but nothing like RemoteCommandArguments. MSDN is not explicit as to if CommandArguments applies to Remove Windows Debugger.
On the other hand, this version of the docs does say that CommandArguments applies to both debuggers: https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/project-settings-for-a-cpp-debug-configuration.md

Tested with version 1.4.0 in VS2015 only.

**Comment by jfmarquis** [comment]
Documentation is outdated and so is that automation interface, according to https://connect.microsoft.com/VisualStudio/feedback/details/833267/vcdebugsettings-class-of-the-visual-c-automation-model-lacks-remotearguments-property

That bug report says to use the new interface IVCRulePropertyStorage. Will look into it.

**Comment by MBulli** [comment]
Thank you for the information. Honestly we didn't knew any better when we started writing the extension. Lately we started to move all code from the old automation api to the new interfaces. Let us know if we should look into this issue or when you need any help.

**Comment by jfmarquis** [comment]
This was actually my first post of any kind on GitHub. In the meantime I
forked the project and will try my suggestions, once I find VS 2017.

**Comment by MBulli** [comment]
Hey any update on that issue? :)

**Comment by jfmarquis** [comment]
I had a PR ready but I realised we still have to set the command line using
the old way to support other platforms. At least the non-Microsoft one I
use at work 😎.
I have yet to try it out there.
Should have the opportunity today, might open PR this weekend.

BTW, I had to update some nuget package version to be able to get them. Is
that normal?
