### ISSUE TITLE
All commandline arguments dissapeared

### ISSUE THREAD

**Issue by Martin877** [MBulli/SmartCommandlineArgs#30]
For some reason all commandlines arguments which I inserted into window disappeared. I have solution with various projects of c++, c++ (linux development) and c# net core app projects. At first I thought that there is problem with multiple solutions, but i wasn't able to reproduce problem yet. I am currently using VS Community 2017 15.2 (26430.6). If I figure any details I will update them here.

**Comment by vincentkarlsson94** [comment]
SmartCommandlineArgs is great, but it lacks the way to change working directory fast.
So I made my own, maybe it works for you?

https://marketplace.visualstudio.com/items?itemName=vk94.FastDebuggingConfig

**Comment by Martin877** [comment]
Ok its not bug, I just needed to set correct project as startup project. closing.
