### ISSUE TITLE
Incompatibility with SwitchStartupProject extension

### ISSUE THREAD

**Issue by ChristianIvicevic** [MBulli/SmartCommandlineArgs#32]
I am using the [*SwitchStartupProject* extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-141975.SwitchStartupProjectforVS2017) and noticed an issue when using together with *SmartCommandlineArgs*.

Here's a sample scenario: There are two projects and a third startup configuration that appends command line arguments in case both projects get executed simultaneously:

```json
{
  "Version": 3,
  "ListAllProjects": true,
  "MultiProjectConfigurations": {
    "Just A": {
      "Projects": {
        "ConsoleApplication1": {}
      }
    },
    "Just B": {
      "Projects": {
        "ConsoleApplication2": {}
      }
    },
    "A and B with overrides": {
      "Projects": {
        "ConsoleApplication1": {
          "CommandLineArguments": "thisWontAppear"
        },
        "ConsoleApplication2": {
          "CommandLineArguments": "thisNeither"
        }
      }
    }
  }
}
```

In all three cases the arguments listed in *SmartCommandlineArgs* are propagated as expected but in the last case when running A and B together they completely overwrite the custom additions. I assume before running the projects your extension completely wipes any additions to the command line arguments.

Is it possible that you introduce an option (or just make it baseline) to append the arguments from your *SmartCommandlineArgs* rather than completely replacing them? (Assuming that *SwitchStartupProject* isn't inejcting their command line arguments in a weird fashion.)

**Comment by MBulli** [comment]
Sorry for the long wait. I wasn't able to reproduce exactly your problem.

In a solution with two console .net framework projects I copied your settings for SwichtStartupProject, added cmd arguments for 'just A/B', and set command arguments in our extension for both projects.

When running 'just A' or 'just B' our arguments appear but not the arguments from SwichtStartupProject.
If running 'A and B' the arguments from SwichtStartupProject are used.

To me it seems that we override the SwichtStartupProject arguments but if more than one startup project is set, we just do nothing.
