### ISSUE TITLE
Arguments not applied to project when using Debug > Start New Instance

### ISSUE THREAD

**Issue by ryani** [MBulli/SmartCommandlineArgs#33]
![image](https://user-images.githubusercontent.com/7133340/32671996-5fb94738-c5fe-11e7-9df9-aea7ae3c23df.png)

Starting a project from Solution Explorer via this method doesn't update its commandline arguments.

**Comment by ryani** [comment]
I use this method to attach the debugger to multiple executables in the same solution (e.g. multiple clients and server).

**Comment by ryani** [comment]
Thanks!

**Comment by MBulli** [comment]
You're welcome. I think we will push a new version soon but I want to revise #29 first.
