### ISSUE TITLE
Feature request: edit commandlines for multiple projects

### ISSUE THREAD

**Issue by ryani** [MBulli/SmartCommandlineArgs#34]
![image](https://user-images.githubusercontent.com/7133340/32672275-4b3322ba-c5ff-11e7-9877-bc5ce259a4ca.png)

- Allow selecting which project within the solution to edit commandline arguments for.
- Store arguments & argument options per project

**Comment by MBulli** [comment]
We're currently experimenting with a new UI design based on a treeview. The goal is to support multiple projects and groups in one take. If its done the list will be a hierarchical view of the solution kinda like this:

- Project 1
  - Group 1
    - arg
  - Group 2
    - arg
    - arg
- Project 2
  - arg

We're also planing to add an option to only show the current startup projects or every project solution. So if only the current project is shown and no groups are created the UI will look like the current version.

I think this new design will also meet your first request. What do you think?

Would you mind to clarify the second bullet point? I'm not sure what you mean.

**Comment by ryani** [comment]
This looks amazing!  The second bullet point is covered by your design--different command-line parameters per-project.

**Comment by MBulli** [comment]
@ryani we just pushed the new version. You can now edit arguments of all projects. Feel free to reopen this issue if something is still missing.
