### ISSUE TITLE
Swithcing from Debug to Release is irrelevant for the extension

### ISSUE THREAD

**Issue by MartinL0815** [MBulli/SmartCommandlineArgs#36]
I have some commandline arguments only valid for debug builds, but I'm unable to distinguish those in the extension to exclude the usage of "debug" command line for a release build.

Is it intended to keep the commandline while swithcing the solution configuration?

**Comment by MBulli** [comment]
Yes, this is intended behavior. This was actually one of the main reasons why we started writing this extension.

**Comment by MartinL0815** [comment]
Ok - than I would suggest to extend the record of a command line to be able to associate a solution configuration or none to automatically disable the command line if the current configuraiton does not match the configured.
Would this be reasonable?

**Comment by MBulli** [comment]
It's definitely reasonable.
In our next release the UI allows you to group several arguments together.
We would add the configuration as a condition applicable to groups.
I think adding this feature on the group level has the most benefit and a nice UX.

But we want to first push the new UI.
