### ISSUE TITLE
Extension fails to load

### ISSUE THREAD

**Issue by MBulli** [MBulli/SmartCommandlineArgs#37]
> Visual Studio 2017 (Prof. Edition) fails loading this plugin since a few days:
> An exception was encountered while constructing the content of this frame. .....
> Exception details:
> System.NullReferenceException: Object reference not set to an instance of an object.
> at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
> at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
> at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
> 
> How to fix it?
> By Wolfgang Vogl

From https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments#qna

**Comment by WolfgangVogl** [comment]
Hello, here's the log file. Reinstalling the extension hadn't fixed the issue.
The Extension has the version 2.0.0 (latest), Visual Studio has the version 15.0.27004.2010
[ActivityLog.txt](https://github.com/MBulli/SmartCommandlineArgs/files/1590600/ActivityLog.txt)

**Comment by MBulli** [comment]
Thanks to the log file I was able to easily spot the faulty code path. Thank you!
For some reason our extension fails to parse its json data from your suo file, which results in a null ref exception at some other code line.

However, I don't see why. I attached a debug build of the extension with additional logging.
Would you mind to install that version, reproduce the error and post the new log file again?
Before installing the debug build you have to manually uninstall the extension int the extension manager.
This would help us to better unterstand the problem.


[SmartCmdArgs-v2.0-debug.zip](https://github.com/MBulli/SmartCommandlineArgs/files/1591332/SmartCmdArgs-v2.0-debug.zip)

**Comment by pps83** [comment]
update totally broke it. I had a clean install of VS 2015, installed the extension and it doesn't work.
I had a working install on another PC that also had the extension and when I updated it I also stopped working. Please roll back the update to previous working build!

**Comment by MBulli** [comment]
@WolfgangVogl  Never mind I found the real cause of the problem.
@pps83  I'm working on a fix for this issue. We're sorry for the inconvenience.

**Comment by pps83** [comment]
As I side note, I built debug version of the extension and it seems that it works now.

**Comment by MBulli** [comment]
It only crashes if the commandline window is opened after a solution was loaded. If you open it before a solution it should not crash

**Comment by MBulli** [comment]
@pps83 I just uploaded a new release here on GitHub and marketplace. The problem should be fixed.

**Comment by WolfgangVogl** [comment]
Just updated the extension from the marketplace - works like a charm! Thank you!
