### ISSUE TITLE
Add a context menu

### ISSUE THREAD

**Issue by MBulli** [MBulli/SmartCommandlineArgs#41]
Possible context menu items are:

- [x] Set as startup project (single startup)
- [ ] Add as startup project (multiple startup projects)
- [x] Create new group from selection
- [x] Select project config (see #36)
- [x] Split command text (see #70)

**Comment by Irame** [comment]
Create new group from selection added with 39ef5ae5bbe95e29eb74c9e64b80d2cabcfe9df0

**Comment by Irame** [comment]
Set as startup project (single startup) added with c8b121c554558efb40aa9a70935993b213a71835

**Comment by Irame** [comment]
Select project config added with b8412fa6bc2e53124677e2b22f37213ba7355400
