### ISSUE TITLE
Error when loading package

### ISSUE THREAD

**Issue by MacTwist** [MBulli/SmartCommandlineArgs#42]
Using VS 2015 version 14.0.25431.01 update 3 and package version 2.0.1.
The package fails to load. I tried uninstalling the package but it always comes back after a restart of visual studio. Activity log shows the following:

574 | ERROR | LegacySitePackage failed for package [CmdArgsPackage]Source: 'SmartCmdArgs' Description: Value cannot be null. Parameter name: jsonStr System.ArgumentNullException: Value cannot be null. Parameter name: jsonStr   at SmartCmdArgs.Logic.ToolWindowSolutionDataSerializer.Deserialize(String jsonStr, VisualStudioHelper vsHelper) in C:\Users\Markus\Documents\GitHub\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\Logic\ToolWindowSolutionDataSerializer.cs:line 32   at SmartCmdArgs.CmdArgsPackage.InitializeForSolution() in C:\Users\Markus\Documents\GitHub\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\CmdArgsPackage.cs:line 457   at SmartCmdArgs.CmdArgsPackage.Initialize() in C:\Users\Markus\Documents\GitHub\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\CmdArgsPackage.cs:line 145   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) | {131B0C0A-5DD0-4680-B261-86AB5387B86E} | 80004003 - E_POINTER | VisualStudio | 2018/01/03 14:12:24.911
-- | -- | -- | -- | -- | -- | --
575 | ERROR | SetSite failed for package [CmdArgsPackage](null) | {131B0C0A-5DD0-4680-B261-86AB5387B86E} | 80004003 - E_POINTER | VisualStudio | 2018/01/03 14:12:24.925
576 | ERROR | End package load [CmdArgsPackage] | {131B0C0A-5DD0-4680-B261-86AB5387B86E} | 80004003 - E_POINTER | VisualStudio | 2018/01/03 14:12:24.929

**Comment by rkhoury** [comment]
I get something similar in VS2017, and my output is:

 type | who | desc | id | errcode
---- | ---- | ---- | ---- | ---- 
Information | VisualStudio | Begin package load [CmdArgsPackage] | {131B0C0A-5DD0-4680-B261-86AB5387B86E} |
Information | SmartCommandlineArgs | Package.Initialize called while solution was already open. | |
Error | VisualStudio | LegacySitePackage failed for package [CmdArgsPackage]Source: &apos;SmartCmdArgs&apos; Description: Value cannot be null.&#x000D;&#x000A;Parameter name: jsonStr&#x000D;&#x000A;System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: jsonStr&#x000D;&#x000A;   at SmartCmdArgs.Logic.ToolWindowSolutionDataSerializer.Deserialize(String jsonStr, VisualStudioHelper vsHelper) in C:\Users\Markus\Documents\GitHub\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\Logic\ToolWindowSolutionDataSerializer.cs:line 32&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.InitializeForSolution() in C:\Users\Markus\Documents\GitHub\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\CmdArgsPackage.cs:line 457&#x000D;&#x000A;   at SmartCmdArgs.CmdArgsPackage.Initialize() in C:\Users\Markus\Documents\GitHub\SmartCommandlineArgs\SmartCmdArgs\SmartCmdArgs\CmdArgsPackage.cs:line 145&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) | {131B0C0A-5DD0-4680-B261-86AB5387B86E} | 80004003 - E_POINTER
Error | VisualStudio | SetSite failed for package [CmdArgsPackage](null) | {131B0C0A-5DD0-4680-B261-86AB5387B86E} | 80004003 - E_POINTER
Error | VisualStudio | End package load [CmdArgsPackage] | {131B0C0A-5DD0-4680-B261-86AB5387B86E} | 80004003 - E_POINTER

**Comment by MBulli** [comment]
It was a stupid oversight from me. It's already fixed a new version is on its way. Thank you for reporting!

**Comment by rkhoury** [comment]
Awesome!  Thanks @MBulli
