### ISSUE TITLE
Selected arguments are lost after restarting VS

### ISSUE THREAD

**Issue by MichaelCoupland** [MBulli/SmartCommandlineArgs#44]
After a recent update to the plugin (I think? I have auto-update enabled in VS and the plugin UI changed slightly...), every time I close and reopen my solution all of my selected arguments (checkboxes) have been deselected. This is very inconvenient - the previous behavior where the checkbox state persisted between runs was much more useful for me!

**Comment by MBulli** [comment]
That is weird. I don't experience that problem and I wonder if more people have the same problem.
The extension stores the checkbox state inside the .suo file. Would you mind to delete or rename that file to check if our stored data is broken for some reason?

However, to reconstruct the problem I need more information. Would you mind [to send us a log file](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log)?

**Comment by MichaelCoupland** [comment]
I've tried but been unable to reproduce this issue since originally encountering it. I'll open a new issue if I can come up with a reliable repro. (And thanks for making a very useful plugin!)
