### ISSUE TITLE
Improve Usability of the TreeView

### ISSUE THREAD

**Issue by MBulli** [MBulli/SmartCommandlineArgs#45]
> Not really a question, but feedback:
> 
> It's not clear where + or +Folder will put the new items. Without anything selected I'd assume it would go to the bottom of the list, or if having a folder selected but it's collapsed, it would also go to the bottom of the list.
> 
> Also, click and dragging of items often ends up removing items from the list which is super frustrating when I'm trying to reorder them.
> 
> Lastly, supporting undo would at least make the above tolerable, instead I lose really long commandlines frequently.
> 
> All in all I love this addon, but the above really hurts productivity when I have to recover long commandlines.
> By Eddie Parker 10 hours ago

**Comment by eddieparker** [comment]
Came here to write this exact bug when I found this.  Thought it incredible that the author had my exact same issue... then I realized this was a copy paste of my comment on the feedback section. :)

Thanks for filing this!  If this does get fixed, let me know if I can test it.  Maybe if I'll get time I'll fork and try to fix it myself, if you accept PR's.

**Comment by MBulli** [comment]
Yeah, I like to quote the issues from marketplace here because communication is more efficient and we can better track the issues.
I also answered you on marketplace. Just in case you missed it, here it is again:
> Would you mind to give us some reproduction steps for your complains? I was only able to reproduce the "add to collapsed folder" problem. However, we are especially interested how arguments get lost while doing drag and drop.
> 
> Hence, detailed steps to reproduce the problem regarding drag and drop and adding items to the list would be highly appreciated.
> If possible please response on the GitHub issue because it's easier to communicate there.

Of course we accept PR's but we also eager to fix issues when we find the time and are able to reproduce them. Either way, let us know how we can help :)

**Comment by eddieparker** [comment]
Sure, let me give some more details on the situations I have issues with:

- I don't know how to add a folder to the root of the commandline arguments window, if I'm not selecting a root level entry.

i.e., empty your command line arguments window, and add a folder.  Now try to add a folder at the same level as the previous folder.  I can't figure out a way of doing this without creating it as a *subfolder*.

Ideally I'd like to be able to 'deselect' the current entry by clicking on any empty space nearby, and then clicking 'folder' or 'item' would add it at the root level.  Optionally having a context menu and/or menubar button for "indent level" or something might work.

- Drag and Drop: delete your command line arguments window contents, and add just one.  Now click and drag it, anywhere on the same window, and it'll disappear from your list of command line arguments.

I also just found out that this tool supports copy/paste, so at least that'll let me 'backup' my command line arguments in case they get destroyed, but undo support would be greatly appreciated. :)

Let me know if my repro's aren't clear enough.

**Comment by MBulli** [comment]
Neither Irame or I could reproduce the case where the arguments get lost.
Can you please somehow Clearing that more?
Maybe its something with your environment or something subtle?

**Comment by MBulli** [comment]
> Drag and Drop: delete your command line arguments window contents, and add just one. Now click and drag it, anywhere on the same window, and it'll disappear from your list of command line arguments.
@eddieparker  Is your command line window by any chances floating? We just found that drag n drop is completely broken if the window floats (see #51)

**Comment by eddieparker** [comment]
Hey MBulli!

Ah-ha!  Yes, it *is* floating.  If I dock it, then my repro's don't work.  If I do float it, it's broken in the way I describe.

Great; I'm not crazy!

**Comment by MBulli** [comment]
That's good to hear. Irame already did some improvements on the UI and we can now fix the drag and drop issue.
