### ISSUE TITLE
Nothing work, getting "unspecified error(Exception from HRESULT: 0x8004005) (E_FAIL)

### ISSUE THREAD

**Issue by qualialibre** [MBulli/SmartCommandlineArgs#47]
Cannot add or remove anything, keep getting this error every time.
When I restart msdev, the add and add-folder executed cuz I see empy lines but I cannot do copy-past command-lines anymore...

**Comment by MBulli** [comment]
It is hard to tell the problem from your issue. Can you please post a [log](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log)?

**Comment by Irame** [comment]
I encountered the same issue today.
It happend while i was working on a C++ project, when i deleted a command group.
Unfortunately was the logging disabled and i couldn't reproduce it.
Please let us know when you have a log file available.

**Comment by MBulli** [comment]
Still unsolved however discussion continues in #52
