### ISSUE TITLE
Deleting from a folder make selection change to random location

### ISSUE THREAD

**Issue by qualialibre** [MBulli/SmartCommandlineArgs#48]
REPRO:
add 10 lines
create folder at 2nd position 
add 3 empty lines in folder
select 2nd line in folder
delete
result: selection is at random place

**Comment by Irame** [comment]
We couldn't reproduce this bug.

Please provide more information regarding:
* the version of VisualStudio
* the version of the extension
* the used project type
* the used input device (mouse/keyboard)

**Comment by MBulli** [comment]
Please reopen this issue if you can provide further information about it
