### ISSUE TITLE
Solution Folders

### ISSUE THREAD

**Issue by FrankDeinzer** [MBulli/SmartCommandlineArgs#5]
If the startup project is located inside a solution folder, then the command line parameters of "Smart Commandline Arguments" are not applied to the project.

**Comment by MBulli** [comment]
This issue ist related to that [code line](https://github.com/MBulli/SmartCommandlineArgs/blob/master/SmartCmdArgs/SmartCmdArgs/CmdArgsPackage.cs#L312).

**Comment by MBulli** [comment]
Fixed with commit ce2ee0a63f01711a47f6c0166f5091149b49f8ad
