### ISSUE TITLE
Crash when clicking anywhere + Delete move down the list and insert a new element

### ISSUE THREAD

**Issue by qualialibre** [MBulli/SmartCommandlineArgs#54]
Context: Solution with 9 projects (one CUDA project), SmartCmdLine has 20 folder(~5 lines each) + 30 individual lines
Msdev was opened for 2 days before clicking for the firts time inside SmartCmdline
Crash occured on click.
Then it inserted a new folder ?!?!

ALSO: Delete of the said folder does delete it but selection carret goes down the list and insert an empty line and select it !?!?!

Screen grab https://ibb.co/fFu2Xo

**Comment by qualialibre** [comment]
CMdLine version : 2.0.4
MSdev version : 
Microsoft Visual Studio Community 2017 
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Version 4.7.02556

**Comment by MBulli** [comment]
We added that box to find the cause of #52. We already have a potential fix (see comment by Irame in #52). Would you mind to test the beta version and ping back to us?!
