### ISSUE TITLE
Doesn't seem to work with TFS

### ISSUE THREAD

**Issue by MBulli** [MBulli/SmartCommandlineArgs#57]
Discussion about TFS from #46.

> That doesn't seem to work either, it was one of the first things we tried because we suspected the same.
> I tried the following:
> 
> Remove suo files
> Start VS
> Select some Arguments
> Run
> Result:
> 
```
   <entry>
     <record>1256</record>
     <time>2018/07/20 06:51:25.757</time>
     <type>Information</type>
     <source>SmartCommandlineArgs</source>
     <description>Tree content changed and VCS support is enabled. Saving all project commands to json file.</description>
   </entry>
    <record>1257</record>
     <time>2018/07/20 06:51:27.856</time>
     <type>Information</type>
     <source>SmartCommandlineArgs</source>
     <description>VS-Event: Startup project will run.</description>
   </entry>
   <entry>
     <record>1258</record>
     <time>2018/07/20 06:51:27.856</time>
     <type>Information</type>
     <source>SmartCommandlineArgs</source>
     <description>Setting arguments on CPS project of type &apos;fae04ec0-301f-11d3-bf4b-00c04f79efbc&apos;.</description>
   </entry>
   <entry>
     <record>1259</record>
     <time>2018/07/20 06:51:27.856</time>
     <type>Information</type>
     <source>SmartCommandlineArgs</source>
     <description>Updated Configuration for Project: Contoso.Northwind</description>
   </entry>
   <entry>
     <record>1260</record>
     <time>2018/07/20 06:51:27.873</time>
     <type>Information</type>
     <source>SmartCommandlineArgs</source>
     <description>Saving commands to suo file.</description>
   </entry>
   <entry>
     <record>1261</record>
     <time>2018/07/20 06:51:27.874</time>
     <type>Information</type>
     <source>SmartCommandlineArgs</source>
     <description>All Commands saved to suo file.</description>
   </entry>
```
> 
> And starts with a different argument that I've selected. For some reason he detects the json file, but still writes (the wrong) stuff to the suo.
> 
> I checked your code and tried to reproduce the issue by opening the file the same way as you do and receive the same exception (as expected, because the json file is not checked out by TFS). If I check the file out, it succeeds.
> 
> Is there a way to debug the extension locally? I cloned the repo and started it, but when working in the experimental VS instance it won't hit any breakpoints in the parent instance ("No symbols loaded").

**Comment by MBulli** [comment]
It should be straightforward to debug the extension locally. Make sure to enable the /RootSuffix Exp commandline and to use the Debug configuration.

This is just a guess: Maybe you have to uninstall the extension from the experimental instance. Then just hit Run in the regular instance and the debug extension should be loaded in the experimental instance. If that works you should be able to code and debug like any other program.

**Comment by lennartb-** [comment]
Managed to get it running, tried to debug in Release config >(
The UnauthorizedAccessException doesn't appear if the file is checked out. The other issue is still present however.
I noticed that the launchSettings.json now plays a role (with the new NET Core project system). Upon starting the correct arguments are entered in the file. However our application gets started with the previously selected arguments.

**Comment by MBulli** [comment]
Well setting the command line arguments from an extension turned out to be surprisingly hard to do... There is no API to rule them all and it wouldn't be the first time MS broke our extension.
I'll check that issue with .NET Core as soon I find some free time.
Which version of visual studio and .NET Core are you using? Which kind of project?

About TFS: Just to clarify, given the file is not checked out, our extension fails to write the arguments to our json file? So that's an issue as well right?

**Comment by lennartb-** [comment]
[Here's](https://gist.github.com/lennartb-/36cd64938c1601a14e51ec924f1ed7c4) a simplified the csproj of the affected project. I'm using VS 2017 15.7.5. It's a C#/WPF project targeting .NET 4.6.1. We don't target .NET Core directly, we're just using the new project system format.

> About TFS: Just to clarify, given the file is not checked out, our extension fails to write the arguments to our json file? So that's an issue as well right?

Yes.

**Comment by MBulli** [comment]
I finally found some time and muse to tackle this issue. To do so I created a free VSTS test project, however VS did not set the readonly flag on my files -.- I did set the workspace mode to server.

But I found the correct APIs to call right before changing a file. Would you mind to test the changes for me? (Haven't done the changes yet)

**Comment by MBulli** [comment]
Never mind, I just found the right setting. Now I can do the tests on my own.

**Comment by MBulli** [comment]
For future reference:

Our extension now call QueryEditFiles() to let VS check out the file. In my tests no UI was shown.
For now we assume that we can always edit the file. If the user cancels or for any other reason CanEditFile() returns false our extension will behave buggy.
