### ISSUE TITLE
Copying the command line causes exception

### ISSUE THREAD

**Issue by MartinL0815** [MBulli/SmartCommandlineArgs#58]
If "copy complete command line" is used, the command line is copied correctly to the clipboard, but an occured exception is signaled by a message box:

> 
![image](https://user-images.githubusercontent.com/525700/42994711-1bb3dd46-8c0f-11e8-956d-98ba900a30eb.png)

I'm running VS2015 on Windows 10 Enterprise Edition

**Comment by MBulli** [comment]
For reference https://stackoverflow.com/a/11726104
