### ISSUE TITLE
Editing a command line argument with display zoom renders incorrectly

### ISSUE THREAD

**Issue by MartinL0815** [MBulli/SmartCommandlineArgs#59]
I use a display zoom of 175% and the height of the edit control to edit in place a command line argument or the row of a command line argument is not high enough.
Please take a look at the screenshot:

> 
![image](https://user-images.githubusercontent.com/525700/42994868-a2732fbc-8c0f-11e8-9f3e-4e1b249c8c47.png)

While moving the caret through the text, the text to be edited jumps some pixels up and down, from being completely visible or like in the screenshot.

**Comment by MBulli** [comment]
![2018-07-21_23-05-02](https://user-images.githubusercontent.com/1533279/43040060-ae833a46-8d3a-11e8-8d49-b8ef17be0729.gif)
