### ISSUE TITLE
The text selection color in high contrast …

### ISSUE THREAD

**Issue by MartinL0815** [MBulli/SmartCommandlineArgs#60]
I need to work with the enabled high-contrast-mode (accessibility helper, switch on/off via LeftAlt+LeftShift+PrintScr).

Trying to select text in the in-place-edit control of an argument looks like this:

> 
![image](https://user-images.githubusercontent.com/525700/42995214-8caecce4-8c10-11e8-9d64-c4d395db0337.png)

Do you have a chance to use the system colors for selections COLOR_HIGHLIGHT/COLOR_HIGHLIGHTTEXT. It should be usable in the high-contrast-environment, so that a user with eye disabilities can see the selection much better.

**Comment by MBulli** [comment]
I think that's actually an issue with WPF? See these 3 screenshots from solution explorer, our extension and a native system dialog.

![highcontrast](https://user-images.githubusercontent.com/1533279/43034955-6f331ed2-8ce6-11e8-9c54-012c70f5ff71.png)

As you can see our extension behaves just like VS does, however the non-WPF UI uses the colors you suggested right?

**Comment by MBulli** [comment]
Its possible to change the color and opacity of the selection but we can't change the text color for the selection. See this answer and comments: https://stackoverflow.com/a/7414017/261645

**Comment by MBulli** [comment]
After rechecking that issue I don't see a way to fix this right now, sorry :(
