### ISSUE TITLE
how to copy text from an argument … or … using the keyboard to work with an argument

### ISSUE THREAD

**Issue by MartinL0815** [MBulli/SmartCommandlineArgs#61]
If I want to copy the text of an argument than Ctrl+C does not work, Ctrl+Ins (the pendant to Ctrl+C) is used by the extension.
If I click again or use F2 to get into the in-place-edit mode, than Ctrl+C does not work either.
Using the right mouse button to open the context menu for edit controls ends the in-place-edit-mode.
Using the context menu key on my keyboard, the context menu with copy, cut, paste comes up and works fine.
The context menu opened by the context menu key on my keyboard lists hotkeys, too. But those do not work entirely:

- Ctrl+V works like Shift-Insert
- Ctrl+C does not work at all
- Ctrl+X copies the selected text, but does not delete it

BTW: using Escape to discard any change in the in-place-edit-mode does not revert changes, but only ends the edit mode.

I'm working with VS2015 and the extension version 2.0.5.

**Comment by MartinL0815** [comment]
Would it be possible to change the Ctrl+Insert hotkey to create a new group, since it overlays the system hotkey to copy something - Ctrl+C and Ctrl+Insert are equivalents and in Germany often Ctrl+Insert is used, not Ctrl+C.

**Comment by MBulli** [comment]
> in Germany often Ctrl+Insert is used, not Ctrl+C.

I never knew that you can use Ctrl/Shift+Insert, and I'm from germany as well :D
We'll check that!

**Comment by MartinL0815** [comment]
;) I'm from old Windows 3.11 times and there was a time, where Ctrl+C/X/V didn't work, while Ctrl/Shift+Ins/Del only worked.
I don't even remember the time, when those "English" and "German" hotkeys started to be work at the same time.

**Comment by MBulli** [comment]
I just changed ctrl+Insert to alt+Insert for adding groups. Maybe there is a better choice for our hotkeys but at the moment I don't know any better. So that one is fixed but:
> Ctrl+C does not work at all

This is strange. Ctrl+C works in every situation you described for me. I have no glue why it doesn't work for you ...

**Comment by MBulli** [comment]
Thinking about #58: Are you using any programs related to the clipboard?

**Comment by MBulli** [comment]
Can't reproduce the Ctrl+C issue. Feel free to reopen this issue.
