### ISSUE TITLE
Go to edit mode when adding new item

### ISSUE THREAD

**Issue by nmoinvaz** [MBulli/SmartCommandlineArgs#66]
This issue is for a feature request. When adding a new item, it should automatically give that item focus AND it should cause that item to go into edit mode where you can enter in text.

Thanks for a great extension! Visual Studio has been lacking this for C projects for many years.

**Comment by nmoinvaz** [comment]
Sometimes I notice also that Control-X does not work when in edit mode. It happens when I try to first paste something in, and then try to cut a portion of it.

**Comment by MBulli** [comment]
Sorry, I overlooked that issue. The new item should have the focus and you can just start typing without entering edit mode explicitly.

![2018-11-07_21-06-19](https://user-images.githubusercontent.com/1533279/48157870-27e28900-e2d1-11e8-902f-71002776fd6b.gif)
