### ISSUE TITLE
CommandLine argument window fails to load

### ISSUE THREAD

**Issue by nmoinvaz** [MBulli/SmartCommandlineArgs#67]
I computer had a power failure, but now in Visual Studio, the plugin will no longer load - even after I tried to uninstall/reinstall.

![image](https://user-images.githubusercontent.com/1364432/47624370-31057600-dad9-11e8-8998-57028221b1c0.png)

![image](https://user-images.githubusercontent.com/1364432/47625331-aa08cb80-dae1-11e8-91db-db3cf9c2811e.png)

Restarting Visual Studio does not help. Here is some lines from the ActivityLog.xml.

```
  <entry>
    <record>695</record>
    <time>2018/10/29 00:37:25.348</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Try to parse solution json: &apos;{&quot;FileVersion&quot;:2,&quot;ShowAllProjects&quot;:false,&quot;CheckedArguments&quot;:[&quot;32822210-19f0-437c-bcd1-e79c09c176a8&quot;,&quot;77acdaab-4c21-40af-876a-9796f902f294&quot;,&quot;ee150481-0c8c-4389-8a03-b102495af032&quot;,&quot;29e53844-6215-44f2-97fe-1c448367e5d9&quot;,&quot;d07f06da-dc54-496c-a4d8-7a666bfa3a51&quot;],&quot;ExpandedContainer&quot;:[&quot;d84d100a-7c21-4ccb-a16e-0fb37137c16c&quot;,&quot;d276bfa8-d118-470c-915b-8a8d981b3ee5&quot;,&quot;3bb49755-376c-4690-b2be-311cec0b8375&quot;,&quot;08eaa26f-c3a6-44fd-abdc-3c94450525a1&quot;,&quot;d00d439f-dc41</description>
  </entry>
  <entry>
    <record>696</record>
    <time>2018/10/29 00:37:25.354</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [CmdArgsPackage]Source: &apos;Newtonsoft.Json&apos; Description: Unterminated string. Expected delimiter: &quot;. Path &apos;ExpandedContainer[3]&apos;, line 1, position 1623.&#x000D;&#x000A;</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>697</record>
    <time>2018/10/29 00:37:25.362</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CmdArgsPackage](null)</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
```

Here is the ActivityLog.xml I threw on Dropbox:
https://www.dropbox.com/s/l5vs682olcdxhpl/ActivityLog.xml?dl=0

I ran the .args.json file for my project through Json Lint and it passed. And removing the .args.json did not help either. Another project of my loads fine with the plugin.

**Comment by nmoinvaz** [comment]
I tried to run process monitor to see what was going on and the problem just disappeared.

**Comment by rkhoury** [comment]
I think this is still an issue, and very much like #64 that I had previously logged.

For me, this issue only manifests when loading Visual Studio solutions *directly from explorer* and that don't contain standard windows toolchain-based targets (I'm working with PS4 and Nintendo Switch solutions that have custom clang-based toolchains and perhaps other properties that cause this issue to flare up).  If I load a default VS instance (in to the start page) and then load these solutions secondary it will work fine. For solutions where I'm using the standard VC140/1 win64-based tools it loads perfectly well.

Another interesting thing I noticed is that when I build the extension myself and debug it (using the experimental instance of VS), these non-win64 solutions load the extension without error.  Further to this, the act loading the solution this way seems to modify the solution's .vs folder databases (.suo and Browse.VC.db) and then any subsequent load from my default default VS instance will work perfectly fine (but only for the solutions loaded by the custom built extension run through the experimental instance, others will still fail).

I don't know if any of this is useful for @MBulli to debug the issue.  I'm not at all familiar with VS Extension programming/debugging to know where to begin debugging this.

**Comment by rkhoury** [comment]
I've attached a zipped solution with a fake Platform definition that always brings up the dialog listed above:
[MyFakeSdkApplication1.zip](https://github.com/MBulli/SmartCommandlineArgs/files/2541106/MyFakeSdkApplication1.zip)
Hopefully that is small enough to be useful for debugging.

**Comment by MBulli** [comment]
Thanks! I'll see if I can find something. The whole issue sounds quite strange to me.

**Comment by rkhoury** [comment]
I'm curious if loading the solution I attached causes this same issue for
you as well.

**Comment by nmoinvaz** [comment]
That solution loads okay for me.

**Comment by rkhoury** [comment]
Hmm. That's confusing.

What version of VS are you using?

**Comment by nmoinvaz** [comment]
2017 15.8.8

**Comment by MBulli** [comment]
Works for me as well in VS (15.8.6). But I can't open it from explorer. I only get this window:

![image](https://user-images.githubusercontent.com/1533279/48030207-a237cf80-e150-11e8-8925-808b15cd3cce.png)

Btw: In the past we had some issues that were only triggered if the solution was loaded while the window was opened and focused or sometimes when the window was closed ...

**Comment by rkhoury** [comment]
Sounds like my particular issue will just have to be debugged locally...

**Comment by MBulli** [comment]
@nmoinvaz I think the power failure corrupted the json (how lucky ...). But I thought our extension is a little more robust regarding faulty json. Nevertheless, we store our data in the json file and in the suo file. In your case the json file failed (and crashed the extension). On the following solution load we just take the data from the suo and rewrite the json file.

@rkhoury Does the log file contain anything useful? Maybe we could add some additional logging.

**Comment by rkhoury** [comment]
Which log file in particular? I'll check it tomorrow and get back to you...

**Comment by MBulli** [comment]
[This one](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log)

**Comment by rkhoury** [comment]
Many thanks!
I'm quite new to the extension development scene so I'm still very much
bumbling my way through.

**Comment by MBulli** [comment]
No worries, I'm not an expert either :D

Am Di., 6. Nov. 2018 um 11:18 Uhr schrieb Richard Khoury <
notifications@github.com>:

> Many thanks!
> I'm quite new to the extension development scene so I'm still very much
> bumbling my way through.
>

**Comment by nmoinvaz** [comment]
@MBulli - I think it might have been the other way around, because I checked the validity of the .json file with a JsonLint parser and it checked out at the time. It is probably the .suo file that got corrupted.

**Comment by MBulli** [comment]
Fair enough, we also use json in the suo ;)

Am Di., 6. Nov. 2018 um 16:11 Uhr schrieb Nathan Moinvaziri <
notifications@github.com>:

**Comment by nmoinvaz** [comment]
@rkhoury - Can you also include your .suo in that zip file?

**Comment by rkhoury** [comment]
Here's the section of the ActivityLog.xml related to this extension loading...
```
  <entry>
    <record>682</record>
    <time>2018/11/06 22:26:35.575</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CmdArgsPackage]</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
  </entry>
  <entry>
    <record>683</record>
    <time>2018/11/06 22:26:35.605</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Package.Initialize called while solution was already open.</description>
  </entry>
  <entry>
    <record>684</record>
    <time>2018/11/06 22:26:35.606</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Try to parse solution json: &apos;&apos;</description>
  </entry>
  <entry>
    <record>685</record>
    <time>2018/11/06 22:26:35.606</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Got empty solution json string. Returning empty ToolWindowStateSolutionData</description>
  </entry>
  <entry>
    <record>686</record>
    <time>2018/11/06 22:26:35.611</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Update commands for project &apos;MyFakeSdkApplication1&apos;. IsVcsSupportEnabled=False. SolutionData.Count=0.</description>
  </entry>
  <entry>
    <record>687</record>
    <time>2018/11/06 22:26:35.612</time>
    <type>Information</type>
    <source>SmartCommandlineArgs</source>
    <description>Gathering commands from configurations for project &apos;MyFakeSdkApplication1&apos;.</description>
  </entry>
  <entry>
    <record>688</record>
    <time>2018/11/06 22:26:35.714</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [CmdArgsPackage]Source: &apos;Anonymously Hosted DynamicMethods Assembly&apos; Description: Cannot perform runtime binding on a null reference&#x000D;&#x000A;</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>80131500</hr>
  </entry>
  <entry>
    <record>689</record>
    <time>2018/11/06 22:26:35.720</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CmdArgsPackage](null)</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>80131500</hr>
  </entry>
  <entry>
    <record>690</record>
    <time>2018/11/06 22:26:35.726</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CmdArgsPackage]</description>
    <guid>{131B0C0A-5DD0-4680-B261-86AB5387B86E}</guid>
    <hr>80131500</hr>
  </entry>
```
And here's the .suo file after initial load:
[suo.zip](https://github.com/MBulli/SmartCommandlineArgs/files/2555272/suo.zip)

**Comment by MBulli** [comment]
Obliviously this is the problem:

`LegacySitePackage failed for package [CmdArgsPackage]Source: 'Anonymously Hosted DynamicMethods Assembly' Description: Cannot perform runtime binding on a null reference`

My guess is that an object returned from VS services is null and on that object we try to call some methods dynamically.

Notice the `LegacySitePackage` part? We need to migrate our extension to `AsyncPackage` sometime. MS won't automatically load non async packages in the future. Maybe this problem is already to that.

**Comment by MBulli** [comment]
We added some null checks and additional logging to the methods we're suspecting to cause the error.
see `GetVCProjEngineAllArguments` and `SetVCProjEngineArguments` in [ProjectArguments.cs:69](https://github.com/MBulli/SmartCommandlineArgs/blob/master/SmartCmdArgs/SmartCmdArgs/Helper/ProjectArguments.cs#L69)

**Comment by rkhoury** [comment]
I tried installing the release config .vsix file but it doesn't seem to
want to target my VS2017 install (it only asks me to install to my VS2015
install).   Is there anything special I have to do at build time to support
a VS2017 install?  I modified the version number from 2.0.6 to 2.0.6.1
thinking that was the issue, but that didn't work.

**Comment by MBulli** [comment]
I forgot to mention that we also pushed a new release 2.0.7, so your VS 2017 might already have the latest version. Otherwise, no there are no special steps.

**Comment by rkhoury** [comment]
Cool! Yes, it has updated on my end now, and it has resolved my issues!!

Many thanks, Markus.

**Comment by MBulli** [comment]
Cool! Does the extension still work? :D
Can you add arguments and they are applied?

The core of the problem is, that there's no 'standard' api call to set the
command line for any project type.
That's also the reason why .Net Core Apps regularly break and why we need
so many null checks etc. Pretty messed up

Am Do., 8. Nov. 2018 um 08:41 Uhr schrieb Richard Khoury <
notifications@github.com>:

> Cool! Yes, it has updated on my end now, and it has resolved my issues!!
>
> Many thanks, Markus.
>
>

**Comment by rkhoury** [comment]
Yes, it still works for me!

**Comment by BengtGustafsson** [comment]
Late to the show... I got this same problem today after having to reboot the computer with VS running. I had 3 different VSes running in different solutions and only one of them fails, so I think it is some data file of yours that is corrupt. So I wonder where those are and how they are named so I can delete the faulty one.

I have "Built target directory" selected for relative path root.
