### ISSUE TITLE
Clipboard operations don't work when editing

### ISSUE THREAD

**Issue by Gargaj** [MBulli/SmartCommandlineArgs#68]
Ctrl-C/X/V doesn't work and there's no rightclick menu to copy/paste either

**Comment by nmoinvaz** [comment]
I also noted that on #66 that sometimes the Control-X does not work when in edit mode.

**Comment by MBulli** [comment]
We already had this issue several times. However, for us copy/paste always worked. I don't know why. But we should add a context menu!

**Comment by Gargaj** [comment]
It does SOMETIMES work, and I haven't been able to nail down the condition when.

**Comment by MBulli** [comment]
Maybe the treeview or window looses the focus? Are you in edit mode?

Am Mi., 7. Nov. 2018 um 10:11 Uhr schrieb Gargaj <notifications@github.com>:

**Comment by Gargaj** [comment]
Okay, I think I found _a_ reason, at least! I use it for a C# project, and if I I have a source (.cs) window focused, Ctrl-X works fine, but if I open a project properties tab, it doesn't. If I switch back to the source tab, it starts working again.

**Comment by MBulli** [comment]
Okay that's clearly reproducible but totally unexplainable. For some reason VS won't create the Copy Command if the property window, explorer window etc. is open. But if the source editor or the solution explorer is 'open' the command is generated. However, we don't do anything special about copy and paste and just use the WPF TextBox, so we have no idea what is happening...

**Comment by nmoinvaz** [comment]
I am using the latest version and for me it has nothing to do with the Properties window. Here is a screen capture of it happening along with the keystrokes.

![editmode](https://user-images.githubusercontent.com/1364432/48292174-267aa300-e42e-11e8-9d55-8598c60b0341.gif)

**Comment by Gargaj** [comment]
@nmoinvaz I noticed that if in the solution explorer you select a source file it starts working again.

**Comment by MBulli** [comment]
![devenv_2018-11-11_21-58-43](https://user-images.githubusercontent.com/1533279/48318228-28df2780-e5fd-11e8-9852-63546e60f90f.png)
![devenv_2018-11-11_21-59-07](https://user-images.githubusercontent.com/1533279/48318229-28df2780-e5fd-11e8-8aaa-edf1266e553c.png)


I think I have to ask that one on the msdn forum because I have no idea why we don't receive the command!

**Comment by Gargaj** [comment]
Is it possibly because the you can cut/copy/paste/etc files, but not the solution itself?

**Comment by MBulli** [comment]
My guess would be yes. However, VS windows like the Output window can handle Ctrl+C while the solution explorer or the project property window is open, so there must be some way to tell VS that we really really want to handle that command (which should be obvious imho).

I think we need to implement the copy/paste by ourselves.

**Comment by MBulli** [comment]
I wrote a post in the MSDN forum but didn't receive any response.

While we can't fix this issue we changed the code which suppressed the system context menu.
