### ISSUE TITLE
Import for launchSettings.json

### ISSUE THREAD

**Issue by nmoinvaz** [MBulli/SmartCommandlineArgs#69]
This issue is for a feature request to have a button in the Commandline Arguments window that would easily enable/disable its use. I know right now you can close the window altogether to disable its use. But then switching between different types of projects, I have to hide/show that window all the time.

**Comment by nmoinvaz** [comment]
In one project, I have a bunch of arguments already setup via launchSettings.json. So on that project, I don't want to use Commandline Arguments, but I have to switch between that solution and others all the time.

Perhaps, there could be an **Import** option for launchSettings.json and each "profile" in launchSettings.json would become a folder with the appropriate command line arguments. In this launchSettings.json I have multiple profiles.

**Comment by Irame** [comment]
With [v3.2](https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v3.2.0) the extension is disabled by default for solutions it has not been used in. If enabled the extension loads all arguments (and other settings like env vars, work dirs and launch apps if the extension is configured to handle them).
This should solve the issue posed and I will therefore close the issue. If it doesn't, you can always reopen the issue.
