### ISSUE TITLE
Split command line arguments up

### ISSUE THREAD

**Issue by nmoinvaz** [MBulli/SmartCommandlineArgs#70]
This issue is for a feature request to be able to easily split up command line arguments from a long command line string into separate items. So if I had a command line string:

`--a --b --c=10`

Then it should split that into three items in the UI.

```
--a
--b
--c=10
```

Maybe some ability or button to **Import** a command line string.

**Comment by MBulli** [comment]
That's something I always wanted too. I think we can implement that when adding a context menu.

**Comment by Irame** [comment]
Implemented with 9054ef6ca2ce9dcefb8fccf8c83b2fef3c1778ee
