### ISSUE TITLE
Radio button style arg support

### ISSUE THREAD

**Issue by Srekel** [MBulli/SmartCommandlineArgs#78]
Here's a screenshot from my current setup. As you can see I can specify which "scenario" (level) my game should start with. Only one (or none!) of these can be active at the same time. 

Sometimes I tick one without remembering to untick another and then the game doesn't start. 

It would be a neat feature if I could somehow link arguments so that they act like radio buttons in that if one is ticked and another one already is, that one gets unticked. But if a ticked button is ticked, it should become unticked, so not _quite_ like a radio button :)

![image](https://user-images.githubusercontent.com/1578924/55056947-f0019580-5067-11e9-972f-dce5ad4f38b4.png)

**Comment by MBulli** [comment]
If you want to link command args you could use groups, but this makes only sense if you split your game setup over several lines.

Regarding the radio button feature we already kinda have that feature. If you click a checkbox while holding down Alt all other checkboxes are disabled. 

Does that help you?

**Comment by Srekel** [comment]
Thanks, using ALT is a workaround that makes it a bit easier to manage at least. :) The feature request still feels reasonable so I'll leave it up to you if you want to close it or not.

I would suggest maybe making it a property/setting of the group?

**Comment by cos-public** [comment]
I would also like to have that feature. So, for example, you could check "Exclusive group items" in a group context menu and checkboxes would behave like ALT is pressed.

**Comment by Irame** [comment]
I implemented a first version of an exclusive mode here 176d4134fa9eaf6a0a02084b02aec852e4a8984e .

An possible addition is to change the checkbox to a radio button when in exclusive mode.

**Comment by Irame** [comment]
This feature is included in version 2.2 
https://github.com/MBulli/SmartCommandlineArgs/releases/tag/v2.2.0
