### ISSUE TITLE
VisualStudio 2015 crash at 2nd instance

### ISSUE THREAD

**Issue by FilRip** [MBulli/SmartCommandlineArgs#80]
Hello,

I report a bug. Visual Studio crash, Windows said it, when (it's very precise) :
- You open 2 (or more) instance of VisualStudio 2015 Pro Update 3 (v14.0.25431.01) (with SmartCommandLineArgs v2.1.0)
- You have open these instances by 2 différents solutions but that are in the same directory.

I hope you understand my description. You see : 2 (différents) solutions in the same directory (that have some (not all) commons projects), the second launch crash visualstudio.

I have try to desactivate this extension, everything work, i reactivate it, it crash, so i think that's come from this extension that i love it, very necessary for me :).

When i ask to debug it (with VisualStudio 2015), i have that (i have it in french, i try to translate it) :
Unhandled exception : System.Runtime.InteropServices.COMException
In : Microsoft.VisualStudio.Shell.14.0.dll
More informations : "GetProperty must be called on the UI thread"
Just that, and it said the debugger is stoped.

Do not hesitate if you need more informations.

Thank you in advance.

**Comment by MBulli** [comment]
Thanks for the detailed report. I think this is the same issue as #79. Should be fixed soon.

**Comment by FilRip** [comment]
Hi,

Version 2.1.1 work like a charm. Thank you

And thank you for this faster fix.
