### ISSUE TITLE
launchSettings.json location and creation

### ISSUE THREAD

**Issue by asherber** [MBulli/SmartCommandlineArgs#83]
The docs say that launchSettings.json will be in the same directory as the project file, but it appears to be created in the Properties folder under the project folder. (This is for framework projects.)

Also, it would be nice if the file were only created when I actually add arguments in the tool window. Right now it seems like the json file gets created whenever I open a solution. I like the idea of the json file, for version control, but I don't want it to be there unless I'm actually using it.

**Comment by MBulli** [comment]
> The docs say that launchSettings.json will be in the same directory as the project file, but it appears to be created in the Properties folder under the project folder. (This is for framework projects.)

With launchSettings.json you mean our *.args.json file? This should be indeed right next to your project file! Which VS version and which project type exactly you're using?

> Also, it would be nice if the file were only created when I actually add arguments in the tool window. Right now it seems like the json file gets created whenever I open a solution. I like the idea of the json file, for version control, but I don't want it to be there unless I'm actually using 

Yep, that's not intended. But again which VS version and project type? On my computer with VS 2017 15.9.7 and a .net framework 4 console app everything works as expected.

**Comment by asherber** [comment]
Sorry, user error, didn't look closely enough. I was working on some projects, and when I went to commit my changes I saw that this file had been created and mistakenly thought it was from this extension. But VS is adding it -- not sure why it just started for me.
