### ISSUE TITLE
Locking a command line.

### ISSUE THREAD

**Issue by Donaldpherman** [MBulli/SmartCommandlineArgs#84]
I find myself accidentally double (instead of single) clicking on the command line and then typing space and F5 deleting the command line.  Can a new feature be added to change a command line to readonly.

**Comment by MBulli** [comment]
I don't think we gonna add that specific feature. Maybe we add a 'lock' button to disable the GUI or even better a nice undo/redo feature. This should also fix your problem.

**Comment by MBulli** [comment]
We added undo/redo functionality.
