### ISSUE TITLE
Hangs on solution load sometimes

### ISSUE THREAD

**Issue by sleepyspider1** [MBulli/SmartCommandlineArgs#85]
In some projects, it hangs when opening the solution.
I think it's when the .json file is missing or something. I have to disable the extension before it will load the solution.

**Comment by MBulli** [comment]
Sadly, without more information we can't do much. Please try to figure out how an when the problem occurs. The specific VS version and project type are also helpful.

Most helpful would be a [log file](https://github.com/MBulli/SmartCommandlineArgs/wiki/Debug-Log) while the issue happened.

**Comment by sleepyspider1** [comment]
It looks like when I launched with devenv.exe /Log <path> and then opened the solution by clicking the solution link on the start page (vs2015), it opened. Now every time I open it, it's fine.
I think it has something to do with doing a fresh checkout from perforce of the project (a unreal4 project), and then double clicking on the .sln file directly is when it hangs.

I will report back if I get it to happen again with logging. But now I can't get it to happen atm.

**Comment by MBulli** [comment]
Feel free to reopen this issue if you can reproduce the error.
