### ISSUE TITLE
Alternate args.json storage location

### ISSUE THREAD

**Issue by drichardson** [MBulli/SmartCommandlineArgs#88]
This is a feature request to use an alternate args.json storage location.

I'm developing with Unreal Engine 4, which generates the visual studio project files. These project files are part of the set of `Intermediate` files which are not meant to be checked into version control and are sometimes deleted as part of development workflow (i.e., building from a pristine state).

I'd like to request that the location of the args.json storage location be able to be in the same directory as the solutions file (.sln). Or, more generally, allow the location to be user specifiable using a visual studio variable like $ProjectDir ([list of variables here](https://docs.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=vs-2017)).

P.S. Besides UE4, I think any visual studio project generating program (e.g., cmake) could suffer from a similar issue.

**Comment by MBulli** [comment]
> P.S. Besides UE4, I think any visual studio project generating program (e.g., cmake) could suffer from a similar issue.

Yes, that's true. I don't know about UE but for cmake we added a msbuild variable which points the extension to the json file. See our wiki here: https://github.com/MBulli/SmartCommandlineArgs/wiki/Cmake-support

Can you use the same mechanism for UE? Basically you have to set $smartCmdArgJsonFile. If it works for UE please let us know so we can add this to our wiki.

**Comment by drichardson** [comment]
I looked into this but didn't figure out how to do it. The problem is that Unreal Engine has it's own tool that generates the Visual Studio projects.

Perhaps a more generic approach would be an enhancement to SmartCommandlineArgs that looks for the args.json file recursively upwards in the file system, starting in the directory that contains the .sln file.

**Comment by drichardson** [comment]
@MBulli I took a look at *CmdArgsPackage.cs* and it appears to make assumptions about *args.json* being part of the project (i.e., calls `vsHelper.CanEditFile(filePath)` where `filePath` is the full path to *args.json*. That makes me think a solution like I proposed (recursively looking up for an *args.json*) may not be completely straightforward.

Can you comment on this? I really like this extension, but at the moment, I lose my argument files all the time because I have to manually save/restore them from the temporary project area Unreal Engine creates.

**Comment by MBulli** [comment]
We still want to fix that but as you noted it might be not that easy. Irame and I don't have much time to spend on this project anymore. 

Can you give us instructions on how to create a hello world project with UE SDK which shows us the problem? Maybe we have an idea when we see how stuff is working with UE.

**Comment by drichardson** [comment]
1. [Install Unreal Engine using the Epic Games Launcher](https://docs.unrealengine.com/en-US/GettingStarted/Installation/index.html). I believe you can also do this as part of the Visual Studio Installer but I haven't tried that method.
2. Launch Unreal Engine and when prompted, choose to create a C++ game. At this point a Visual Studio SLN will be generated in the same folder your game is in, with generated project files stored in the *Intermediate\ProjectFiles* sub-directory.

**Comment by MBulli** [comment]
Sure, we can store the arguments next to sln file. We could add an option to enable this. Also, we would then store all arguments from every project in one args.json file named after the solution. Does that work for you?

**Comment by drichardson** [comment]
Yes, that'd be perfect. I just need it to be outside of that directory (*Intermediate\ProjectFiles*) that gets deleted from time to time so I don't lose the arguments I've taken the time to setup.

**Comment by drichardson** [comment]
One other thing to note, the SLN file is also automatically generated, so if any data referencing the file is stored in it, it will be lost the next time a project file generation occurs (which is whenever a C++ .h or .cpp file is added to the project).

**Comment by MBulli** [comment]
In that case we have to add the option globally to VS.

**Comment by chrisaverage** [comment]
Hi, I'm in a similar position where we use a custom build toolchain that regenerates solution and project files (not UE). Solution location is also temporary in my case and gets purged occasionally.

Could you add a more general option to specify a directory (ideally outside of the source tree) where args.json is stored? It could create a sub-directory in it for each solution path or something like that.
