### ISSUE TITLE
Add support for other types of Projects

### ISSUE THREAD

**Issue by Cellule** [MBulli/SmartCommandlineArgs#9]
I would like to add support for different types of projets.
I started looking into an abstraction to get/set the command line arguments on different kinds of projects.

Right now, I got a somewhat working solution for Python projects (will need a change in the Python extension).

List of projects to add support
- [x] [Python Projects](https://github.com/Microsoft/PTVS)
- [x] [NodeJs Projects](https://github.com/Microsoft/nodejstools)

These are the types of projects I use regularly.
If people are interested in a wider support we could look into that.

I already have the code ready for the abstraction layer, I can submit the PR now if there's interest

**Comment by MBulli** [comment]
Go ahead and submit the PR. Support for other projects is highly appreciated. I already tried to add Python support but failed because of the missing setter.

**Comment by Cellule** [comment]
My PR for python project was merged today. I don't know how long it will take until PTVS releases a new version, but sometime soon it should work :D

**Comment by MBulli** [comment]
FYI: They just released PTVS v.2.2.4 but it seems that your PR is not included yet.

**Comment by Irame** [comment]
The VisaulStudio 15.2 update brought the Python workload, this enables us to support Python fully in VS 2017!
