### ISSUE TITLE
Improve finding the views via VS Search (Ctrl+Q)

### ISSUE THREAD

**Issue by jbuedel** [MBulli/SmartCommandlineArgs#91]
It can be a little hard to find the ui bits when using the Visual Studio search box. The obvious search keywords ("command line", "smart", etc) offer links to the "Options->Smart Command Line Arguments->General" pretty easily. However it's tricky to get "View->Other Windows->Commandline Arguments" to show up. 

I think it could be helped by using a consistent name everywhere. Specifically, it's called "Smart Command Line Arguments" in the options panel, "Commandline Arguments" in Other Windows, and "Command Line Arguments" is the title on the actual window.  I suggest "Smart Command Line Arguments" in all these places.

**Comment by MBulli** [comment]
I see your point there but we want to keep 'Command Line Arguments' as window title as the whole extension name is quite wordy. However, I fixed the title in the View menu, but kept the name in the options.

I also tried to provide some search keywords for quick launch but couldn't find any way doing so.

**Comment by jbuedel** [comment]
Thanks. Really love the tool. I've got my coworkers using it now as well.
