### ISSUE TITLE
Arguments configuration is not loaded after "Reload project" context menu.

### ISSUE THREAD

**Issue by cos-public** [MBulli/SmartCommandlineArgs#92]
It seems that arguments configuration is not loaded on "Reload project" context menu action.

**Comment by Irame** [comment]
Hi, sry for the late response.
We can't reproduce the issue and have a few questions:
1. Which version of VS are you using?
2. What kind of project are you using?
3. What are the steps to reproduce the issue?

**Comment by cos-public** [comment]
Visual Studo 16.5.4
Visual C++ project (native vcxproj + sln files)
Steps:
1. Open any project with command line arguments configured.
2. Right click a project entry in the Solution Explorer tree and select "Unload Project".
3. The project entry in the tree becomes "<project name> (unloaded)"
4. Right click the project entry in the Solution Expolorer and pick "Reload Project".

Result: Command Line Arguments pane is empty
Expected: Command Line Arguments for the project are reloaded

**Comment by Irame** [comment]
see #94
