### ISSUE TITLE
SmartCommandlineArgs erases default `Command arguments` with an empty string

### ISSUE THREAD

**Issue by pps83** [MBulli/SmartCommandlineArgs#93]
I filled relevant issue in [ConcordExtensibilitySamples](https://github.com/microsoft/ConcordExtensibilitySamples/issues/54). That's a sample project for a c++ visualizer. In that project, be default, if you F5 debug build of `vsix` project it starts a new instance of VS with the extension loaded to be able to debug the extension itself. For me it totally didn't work, turned out that SmartCommandlineArgs erases default cmd in that project.

**Comment by MBulli** [comment]
This is fixed with #105. Now a dialog will ask you what to do with the project command lines. Sorry for the trouble!
