### ISSUE TITLE
Empty window that is locked

### ISSUE THREAD

**Issue by agreysukh** [MBulli/SmartCommandlineArgs#94]
Just installed to MVS 2015.  Popped up  a blank unresponsive window.

**Comment by MBulli** [comment]
Just did the same and worked. Would you mind to provide more infos?

**Comment by RealHandy** [comment]
Newest VS 2019, same thing -- The commandline args window is empty and all the buttons are greyed out except for show all projects and search.

**Comment by Irame** [comment]
I guess the response is a bit too late for the original issue authors, but i stumbled upon the problem by unloading the startup project and loading it again.
In this case VisualStudio sets the newly loaded project as the startup project but our extension does not recognize this and has no active startup project. This can be confirmed by toggling the "Show all projects" button on, where no project is bold (normally highlighting the startup project).

**A workaround for now is to right-click the startup project and set it as the startup project again.**

**Comment by Irame** [comment]
This should be fixed with the next version (f8348a917385c4b5ce8238a1fd3ee9be2fefdbe7)
