### ISSUE TITLE
Set font

### ISSUE THREAD

**Issue by andrew-gresyk** [MBulli/SmartCommandlineArgs#99]
Very cool extension, such a timesaver for an Unreal Engine game development.

Could you add a config for the font used in the pane?
Or, use the font from Solution Explorer or any other VS pane?

Thanks.

**Comment by MBulli** [comment]
We'll look into that. I would prefer to use the VS font, if we can.

**Comment by MBulli** [comment]
![image](https://user-images.githubusercontent.com/1533279/81477879-689ac580-921a-11ea-86c5-8e7b92cf5566.png)

We now use the 'Environment' font family and size.

**Comment by andrew-gresyk** [comment]
Thanks Markus
